Seperate RenderItemChangeY into its own mixin and disable that when canvas is present.
shedaniel/slight-gui-modifications pull request #11
Opened 2020-11-28 21:23 UTC by loper12

Fixes #10. All this does is disable RenderItemChangeY when canvas is present. This isn't the best solution, but the next best solution would probably be along the lines of adding canvas compatibility.

2020-11-28 21:28 UTC, shedaniel requested changes
looks fine apart from that small change

2020-11-28 21:28 UTC, shedaniel commented on src/main/resources/fabric.mod.json
> +    "item-renderer.mixins.json"
can you prefix this with the mod id

2020-11-28 21:32 UTC, loper12 commented on src/main/resources/fabric.mod.json
> +    "item-renderer.mixins.json"
ok

2020-11-29 16:22 UTC, loper12 commented
I've realized that I can clean this all into the one plugin, which may make it easier to add incompatibilities. Will do this, unless you'd like to object.

2020-11-29 16:25 UTC, shedaniel commented
It is fine

2020-11-29 16:27 UTC, loper12 commented
Fine for me to add it? or fine as it is? I'd be completely fine to add it, but if you'd like me to leave it as it is, it is ok.

2020-11-29 16:39 UTC, shedaniel commented
It is fine for you to add it

2020-11-29 16:47 UTC, loper12 commented
Done.

2020-11-29 16:57 UTC, shedaniel approved these changes

2020-11-29 16:57 UTC, merged